name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (Service Account Key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker \
            ${{ secrets.LOCATION }}-docker.pkg.dev \
            --quiet
      
      - name: Install GKE gcloud auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials my-clus\
            --zone ${{ secrets.LOCATION }} \
            --project ${{ secrets.PROJECT_ID }}

      - name: Build & Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/fastapi

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to GKE
        run: |
          IMAGE_URI=${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/fastapi

          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          kubectl set image deployment/${{ secrets.DEPLOYMENT_NAME }} \
            fastapi=$IMAGE_URI

          kubectl rollout status deployment/${{ secrets.DEPLOYMENT_NAME }}
          kubectl get svc -o wide
